### ISSUE TITLE
windows-terminal-quake can't run wt.exe

### ISSUE THREAD

**Issue by m1k0lay** [flyingpie/windows-terminal-quake#61]
![Безымянный](https://user-images.githubusercontent.com/39671588/105137093-d3b7ce00-5b03-11eb-85f8-a0b3f140a461.jpg)

**Comment by flyingpie** [comment]
Hey @m1k0lay! Thank you for reporting the issue :) Could you provide a translation, since my Russian currently is a bit rusty :D

**Comment by m1k0lay** [comment]
"Couldn't find the specified file"

**Comment by flyingpie** [comment]
Thanks you for helping me out :)

- What version are you running?
- What version of Windows Terminal are you running?
- Could you add the following to the .json file: ```"Logging": true```, then start again and see if a log file is created (paste here if so).
- Are you running the tool from a folder with a space in it by any chance? This should be fixed in a recent version.

**Comment by m1k0lay** [comment]
- 1.1.0
- 1.4.32.43

> `2021-01-21 21:17:30.352 +03:00 [INF] Windows Terminal Quake started
2021-01-21 21:17:30.445 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-01-21 21:17:30.474 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-01-21 21:17:30.538 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-01-21 21:17:30.648 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-01-21 21:17:30.913 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-01-21 21:17:31.427 +03:00 [WRN] Error: Не удается найти указанный файл
System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
   в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   в WindowsTerminalQuake.Native.TerminalProcess.GetOrCreate(String[] args)
   в WindowsTerminalQuake.Native.TerminalProcess.<>c__DisplayClass6_0.<Get>b__0()
   в Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   в Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   в Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   в Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   в Polly.Policy.Execute[TResult](Func`1 action)
   в WindowsTerminalQuake.Toggler..ctor(String[] args)
   в WindowsTerminalQuake.Program.Main(String[] args)`
- yes

**Comment by flyingpie** [comment]
@m1k0lay Could you try to run both apps from a folder with no spaces? It _should_ work, but that way we can figure out if that's the problem.

**Comment by m1k0lay** [comment]
> @m1k0lay Could you try to run both apps from a folder with no spaces? It _should_ work, but that way we can figure out if that's the problem.

`2021-02-13 19:24:45.922 +03:00 [INF] Windows Terminal Quake started
2021-02-13 19:24:46.005 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-02-13 19:24:46.036 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-02-13 19:24:46.097 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-02-13 19:24:46.203 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-02-13 19:24:46.462 +03:00 [ERR] Error creating process: 'Не удается найти указанный файл'
2021-02-13 19:24:46.969 +03:00 [WRN] Error: Не удается найти указанный файл
System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
   в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   в WindowsTerminalQuake.Native.TerminalProcess.GetOrCreate(String[] args)
   в WindowsTerminalQuake.Native.TerminalProcess.<>c__DisplayClass6_0.<Get>b__0()
   в Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   в Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   в Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   в Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   в Polly.Policy.Execute[TResult](Func`1 action)
   в WindowsTerminalQuake.Toggler..ctor(String[] args)
   в WindowsTerminalQuake.Program.Main(String[] args)
`

**Comment by fmiqbal** [comment]
I got similar error recently, 
I am using version 1.1.1
I am on `Windows Insider Build 21327.1000`
it doesn't reported on event viewer

I am running in `D:\terminal`
![image](https://user-images.githubusercontent.com/8409391/109965770-015a7e80-7d22-11eb-9d8e-cd345e54c9a8.png)
![image](https://user-images.githubusercontent.com/8409391/109965805-0c151380-7d22-11eb-8175-1ed9b1abf52a.png)

**Log files**
```
2021-03-04 19:45:20.642 +07:00 [INF] Windows Terminal Quake started
2021-03-04 19:45:21.182 +07:00 [ERR] Error creating process: 'The system cannot find the path specified'
2021-03-04 19:45:21.225 +07:00 [ERR] Error creating process: 'The system cannot find the path specified'
2021-03-04 19:45:21.302 +07:00 [ERR] Error creating process: 'The system cannot find the path specified'
2021-03-04 19:45:21.430 +07:00 [ERR] Error creating process: 'The system cannot find the path specified'
2021-03-04 19:45:21.697 +07:00 [ERR] Error creating process: 'The system cannot find the path specified'
2021-03-04 19:45:22.228 +07:00 [WRN] Error: The system cannot find the path specified
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at WindowsTerminalQuake.Native.TerminalProcess.GetOrCreate(String[] args)
   at WindowsTerminalQuake.Native.TerminalProcess.<>c__DisplayClass6_0.<Get>b__0()
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at WindowsTerminalQuake.Toggler..ctor(String[] args)
   at WindowsTerminalQuake.Program.Main(String[] args)
```

**Comment by fmiqbal** [comment]
I may have problem on my end, not the project 

![image](https://user-images.githubusercontent.com/8409391/109968587-7bd8cd80-7d25-11eb-9b8f-557f49f18335.png)

**Comment by flyingpie** [comment]
@m1k0lay There have been a couple mentions of this issue by now, and I wonder if wt.exe is not fully available from all contexts on every machine.

Anyway, I added a setting called "WindowsTerminalCommand" in a new release. If you could try this, changing the path to the actual path to wt.exe:

```json
{
	"WindowsTerminalCommand": "C:\\Users\\path\\to\\wt.exe"
}
```

This setting allows for configuring the path to wt.exe manually, so we don't need to rely on it being available through and environment variable.

The release can be found here ('windows-terminal-quake-1.2.0-2021-04-30_1752.zip'):

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

**Comment by m1k0lay** [comment]
![Снимок экрана 2021-05-19 165628](https://user-images.githubusercontent.com/39671588/118825312-3e66f380-b8c3-11eb-90c7-7dd5982b7819.jpg)
![Безымянный](https://user-images.githubusercontent.com/39671588/118825315-3f982080-b8c3-11eb-8d82-3a1920255214.jpg)

**Comment by m1k0lay** [comment]
![image](https://user-images.githubusercontent.com/39671588/118883033-7a1eaf00-b8fd-11eb-88b8-c6ecf1c269c2.png)
